
import { Episode, PatientInfo } from './types';

export const patientInfo: PatientInfo = {
  name: "ROBERTSON, ARTHUR",
  dob: "1958-06-12 (67y)",
  id: "MRN-8829103",
  sex: "Male",
  primaryDx: "Idiopathic Pulmonary Fibrosis (IPF); S/P Tibial Fracture ORIF"
};

export const episodes: Episode[] = [
  {
    Episode_Number: 1,
    Date_Start: "2024-01-15",
    Date_End: "2024-01-15",
    Episode_Type: "ED Visit",
    Chief_Complaint: "Right leg pain after fall; SOB",
    Department: "Emergency Department",
    Provider: "Dr. Martinez MD",
    BP_Systolic: "145",
    BP_Diastolic: "88",
    Heart_Rate: "92",
    Respiratory_Rate: "22",
    SpO2_Room_Air: "89",
    Interventions: "X-ray R tibia/fibula; oxygen 3L NC; splint application",
    Medications: "Morphine 4mg IV; Ondansetron 4mg IV",
    Disposition: "Admitted to Ortho"
  },
  {
    Episode_Number: 2,
    Date_Start: "2024-01-15",
    Date_End: "2024-01-19",
    Episode_Type: "Inpatient",
    Chief_Complaint: "ORIF right tibial shaft fracture",
    Department: "Orthopedic Surgery",
    Provider: "Dr. Chen MD",
    BP_Systolic: "132",
    BP_Diastolic: "75",
    Heart_Rate: "78",
    Respiratory_Rate: "20",
    SpO2_With_O2: "91",
    O2_Liters: "2",
    Interventions: "ORIF with IM nail 01/16; PT consult; wound care",
    Medications: "Enoxaparin 40mg SQ daily; Oxycodone 5mg q4h PRN; Ceftriaxone 1g IV q24h",
    Disposition: "Discharged home",
    Follow_Up: "Ortho clinic 2 weeks"
  },
  {
    Episode_Number: 3,
    Date_Start: "2024-02-02",
    Date_End: "2024-02-02",
    Episode_Type: "Outpatient",
    Chief_Complaint: "Post-op follow-up; wound check",
    Department: "Orthopedic Clinic",
    Provider: "Dr. Chen MD",
    BP_Systolic: "128",
    BP_Diastolic: "82",
    Heart_Rate: "74",
    SpO2_Room_Air: "92",
    Interventions: "Wound inspection; X-ray R tibia",
    Medications: "Continue Aspirin 81mg daily; D/C Oxycodone; start Tramadol 50mg q6h PRN",
    Disposition: "Routine discharge",
    Follow_Up: "Return 4 weeks"
  },
  {
    Episode_Number: 4,
    Date_Start: "2024-03-18",
    Date_End: "2024-03-18",
    Episode_Type: "Outpatient",
    Chief_Complaint: "Worsening dyspnea; dry cough",
    Department: "Pulmonology Clinic",
    Provider: "Dr. Patel MD",
    BP_Systolic: "138",
    BP_Diastolic: "84",
    Heart_Rate: "88",
    Respiratory_Rate: "24",
    SpO2_Room_Air: "87",
    Interventions: "PFTs (FVC 58% predicted; DLCO 42%); HRCT chest ordered",
    Medications: "Pirfenidone 801mg TID; home O2 2-4L PRN",
    Disposition: "Routine discharge",
    Follow_Up: "Return 8 weeks"
  },
  {
    Episode_Number: 5,
    Date_Start: "2024-05-12",
    Date_End: "2024-05-12",
    Episode_Type: "Outpatient",
    Chief_Complaint: "Bone healing assessment",
    Department: "Orthopedic Clinic",
    Provider: "Dr. Chen MD",
    BP_Systolic: "135",
    BP_Diastolic: "80",
    Heart_Rate: "76",
    SpO2_Room_Air: "93",
    O2_Liters: "2",
    Interventions: "X-ray R tibia - callus formation noted; gait assessment",
    Medications: "Continue current meds",
    Disposition: "Discharged to PT",
    Follow_Up: "Return 8 weeks; PT 2x/week"
  },
  {
    Episode_Number: 6,
    Date_Start: "2024-07-22",
    Date_End: "2024-07-22",
    Episode_Type: "Outpatient",
    Chief_Complaint: "Routine IPF monitoring",
    Department: "Pulmonology Clinic",
    Provider: "Dr. Patel MD",
    BP_Systolic: "142",
    BP_Diastolic: "86",
    Heart_Rate: "82",
    Respiratory_Rate: "22",
    SpO2_Room_Air: "90",
    SpO2_With_O2: "95",
    O2_Liters: "3",
    Interventions: "PFTs (FVC 55% predicted; DLCO 39%); CXR",
    Medications: "Continue Pirfenidone; increase O2 to continuous use; add Omeprazole 20mg daily",
    Disposition: "Routine discharge",
    Follow_Up: "Return 8 weeks"
  },
  {
    Episode_Number: 7,
    Date_Start: "2024-09-30",
    Date_End: "2024-09-30",
    Episode_Type: "Outpatient",
    Chief_Complaint: "Final ortho clearance",
    Department: "Orthopedic Clinic",
    Provider: "Dr. Chen MD",
    BP_Systolic: "130",
    BP_Diastolic: "78",
    Heart_Rate: "74",
    SpO2_Room_Air: "94",
    O2_Liters: "2",
    Interventions: "X-ray R tibia - union complete",
    Medications: "D/C Tramadol",
    Disposition: "Discharged from Ortho",
    Follow_Up: "PRN only"
  },
  {
    Episode_Number: 8,
    Date_Start: "2024-11-08",
    Date_End: "2024-11-08",
    Episode_Type: "ED Visit",
    Chief_Complaint: "Acute dyspnea; productive cough; fever",
    Department: "Emergency Department",
    Provider: "Dr. Rodriguez MD",
    BP_Systolic: "152",
    BP_Diastolic: "92",
    Heart_Rate: "108",
    Respiratory_Rate: "28",
    SpO2_Room_Air: "84",
    Temperature_C: "38.4",
    Interventions: "CXR; CBC; BMP; blood cultures; sputum culture",
    Medications: "Ceftriaxone 1g IV; Azithromycin 500mg IV; O2 5L NC",
    Disposition: "Admitted to Medicine"
  },
  {
    Episode_Number: 9,
    Date_Start: "2024-11-08",
    Date_End: "2024-11-13",
    Episode_Type: "Inpatient",
    Chief_Complaint: "Acute exacerbation IPF vs pneumonia",
    Department: "Internal Medicine",
    Provider: "Dr. Williams MD",
    BP_Systolic: "135",
    BP_Diastolic: "82",
    Heart_Rate: "84",
    Respiratory_Rate: "22",
    SpO2_With_O2: "92",
    O2_Liters: "4",
    Interventions: "IV antibiotics; respiratory therapy; ID consult",
    Medications: "Meropenem 1g IV q8h; Methylprednisolone 40mg IV q12h; continue Pirfenidone when tolerating PO",
    Disposition: "Discharged home with HHC",
    Follow_Up: "Pulmonology clinic 1 week"
  },
  {
    Episode_Number: 10,
    Date_Start: "2025-01-20",
    Date_End: "2025-01-20",
    Episode_Type: "Outpatient",
    Chief_Complaint: "Post-hospitalization F/U; declining function",
    Department: "Pulmonology Clinic",
    Provider: "Dr. Patel MD",
    BP_Systolic: "145",
    BP_Diastolic: "88",
    Heart_Rate: "90",
    Respiratory_Rate: "26",
    SpO2_Room_Air: "88",
    O2_Liters: "4",
    Interventions: "PFTs (FVC 48% predicted; DLCO 35%); palliative care referral; 6MWT 180m",
    Medications: "Continue Pirfenidone; Prednisone taper 20mg daily x 2weeks; O2 continuous 4-6L",
    Disposition: "Routine discharge",
    Follow_Up: "Return 4 weeks; Palliative consult"
  }
];
